"""phase6_audit_logs

Revision ID: c70d1e4a0040
Revises: 10ec8b01c1ab
Create Date: 2026-09-05 07:51:40.464508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70d1e4a0040'
down_revision: Union[str, None] = '10ec8b01c1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('login', 'logout', 'upload', 'view', 'download', 'update', 'rename', 'move', 'delete', 'restore', 'permanent_delete', 'version_create', 'version_restore', 'folder_create', 'folder_update', 'user_create', 'user_update', 'role_change', 'permission_change', 'ocr_process', 'ocr_failure', 'department_create', 'department_update', name='audit_action'), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', name='audit_result'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_department_id'), 'audit_logs', ['department_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_document_id'), 'audit_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_document_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_department_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
